config-version: 0.1
debugMode: false
defaultMaxLevel: 100
defaultBaseExperienceRequirement: 10
defaultExperienceIncreaseFactor: 1.2
levelUpAlert: true
benefitAlert: true
boatSpeedBenefitEnabled: true
athleteBenefitEnabled: true
cardioBenefitEnabled: true
glidingBenefitEnabled: true
ridingBenefitEnabled: true
hardinessBenefitEnabled: true
strengthBenefitEnabled: true
duelingBenefitEnabled: true
monsterHuntingBenefitEnabled: true
woodcuttingBenefitEnabled: true
miningBenefitEnabled: true
fishingBenefitEnabled: true
breedingBenefitEnabled: true
craftingBenefitEnabled: true
diggingBenefitEnabled: true
enchantingBenefitEnabled: true
farmingBenefitEnabled: true
floricultureBenefitEnabled: true
pyromaniacBenefitEnabled: true
quarryingBenefitEnabled: true
