name: '${project.name}'
version: '${project.version}-${devbuid.version}'
main: dansplugins.simpleskills.SimpleSkills
api-version: 1.13
author: Daniel Stephenson

commands:
  simpleskills:
  ss:
  skills:

permissions:
  ss.help:
    default: true
  ss.info:
    default: true
  ss.top:
    default: true
  ss.stats:
    default: true
  ss.skill:
    default: true
  ss.force:
    default: op
  ss.force.wipe:
    default: op
  ss.force.activate:
    default: op
  ss.force.deactivate:
    default: op
  ss.reload:
    default: op