name: SimpleSkills
version: 0.8-alpha-1
main: dansplugins.simpleskills.SimpleSkills
api-version: 1.13
author: Daniel Stephenson

commands:
  simpleskills:
  ss:

permissions:
  ss.help:
    default: true
  ss.info:
    default: true
  ss.top:
    default: true
  ss.stats:
    default: true
  ss.skill:
    default: true
  ss.config:
    default: op
  ss.wipe:
    default: op