name: SimpleSkills
version: v0.4-alpha-1
main: dansplugins.simpleskills.SimpleSkills
api-version: 1.13

commands:
  simpleskills:
  ss:

permissions:
  ss.help:
    default: true
  ss.info:
    default: true
  ss.top:
    default: true
  ss.stats:
    default: true
  ss.config:
    default: op